---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-restart-pod
  namespace: <YOUR NAMESPACE>
spec:
  concurrencyPolicy: Forbid
  schedule: '*/2 * * * *' # every 2 min
  jobTemplate:
    spec:
      backoffLimit: 2 # this has very low chance of failing, as all this does is prompt kubernetes to schedule new replica set for the deployment
      activeDeadlineSeconds: 600 # timeout, makes most sense with "waiting for rollout" variant specified below
      template:
        spec:
          serviceAccountName: cron-sa
          restartPolicy: Never
          containers:
            - name: k8s-cron
              image: feliux/k8s-cron:<version>-golang
              command: ["/app"] # golang
              args: ["-auth=inside", "-namespace=foo", "-deployment-name=bar", "-change-cause=baz"] # golang
              #image: feliux/k8s-cron:<version>-python
              #command: ["python"] # python
              #args: ["main.py", "-a", "inside", "-ns", "foo", "-deploy", "bar", "-cc", "baz"] # python