apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    
    - name: 'PostgreSQL PinPon'
      type: postgres
      url: 'psql-pinpon-svc.pinpon.svc.cluster.local'
      database: pinpon
      user: grafana
      secureJsonData:
        password: 'jwenfie!T'
      jsonData:
        sslmode: 'disable'

    - name: Google Cloud Monitoring
      type: stackdriver
      access: proxy
      jsonData:
        authenticationType: gce
