{
 "title": "PinPon Previous",
 "tags": [ "PinPon" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "query": "select distinct(home_participant) from previous_setka_cup_others_men"
   }
  ]
 },
 "panels": [
  {
   "title": "Previous Matches",
   "type": "table",
   "description": "Results of previous matches",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select distinct(date), home_participant, home_score, away_score, away_participant,\ndiff_sets, diff_points,\nhome_total_points, away_total_points,\nhome_event_part1 as home_part1, away_event_part1 as away_part1,\nhome_event_part2 as home_part2, away_event_part2 as away_part2,\nhome_event_part3 as home_part3, away_event_part3 as away_part3,\nhome_event_part4 as home_part4, away_event_part4 as away_part4,\nhome_event_part5 as home_part5, away_event_part5 as away_part5\nfrom previous_setka_cup_others_men\nwhere $__timeFilter(date) and \n(home_participant in ($player) or away_participant in ($player))\norder by date desc"
    }
   ]
  }
 ]
}
{
 "title": "PinPon Stats",
 "tags": [ "PinPon" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "setka_men",
    "query": "select player from stats_setka_cup_others_men"
   },
   {
    "name": "pro_men",
    "query": "select player from stats_liga_pro_others_men"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Instrucciones\n\n  1. Selecciona el jugador en la pestaña superior `setka_men`, `pro_men` para filtrar la búsqueda. Ten en cuenta que el formato de nombres es en primer lugar el apellido seguido de la primera letra del nombre. Las estadísticas para cada jugador se mostrarán en las tablas inferiores\n 2. Click en el dashboard que quieres visualizar (por ejemplo **Setka Cup Men**).\n 3. Scroll-down para ver todas las tablas.\n\n \n\n # Instructions\n\n  1. Select your player in the above tab `setka_men`, `pro_men` to filter by name. Format is surname and first letter name. This players will be shown on the following panels\n 2. Click on the dashboard you want to visualize (for example **Setka Cup Men**). You will see various statistics of the previously selected players.\n 3. Scroll-down to see all the tables."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Setka Cup Men",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "options": {
      "content": "- **Stats for sets**: media de sets con valores positivos y negativos y su correspondiente desviación típica (std). Valores negativos indican que el jugador ha perdido más sets de los que ha ganado (y viceversa). Si `mean = 0` entonces el jugador ha ganado tantos partidos como los que ha perdido. El valor de **%** indica el número de sets ganados/perdidos según el percentil (25, 50, 75). Por ejemplo, si `25% = 2` entonces podemos decir que para el **25%** total de partidos, el jugador ha ganado **2** sets por encima de sus oponentes. Otro ejemplo: `75% = -1` entonces el **75%** de partidos, el jugador ha finalizado con **1** set por debajo de su oponente. En resumen, valores positivos indican buenos jugadores mientras que valores negativos son sinónimos de malos jugadores.\n - **Stats for points**: aplica la misma dinámica explicada que para *Stats for sets* pero esta vez para la diferencia entre puntos totales.\n\n ---- \n\n- **Stats for sets**: sets mean with values -/+ corresponding with typical desviation (std). Mean negative values ​​indicate that the player has lost more sets than he has won (and viceversa). If `mean = 0` then the player has won the same number of sets he lost. The interpretation of **%** is a bit different, it indicate in which percentile are the number of sets. For example, if `25% = 2` then we can say that for the **25%** total of matches, the player has won with **2** sets above of his opponent. Another example: if `75% = -1` then for the **75%** total of matches, the player has lost with **1** sets below his opponent. Consider that positive values indicate a good player and negative values are synonymous of bad players.\n - **Stats for points**: the same as *Stats for sets* but in this case for total points differences."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Next matches",
     "type": "table",
     "description": "Next matches for the player who has at least 1 stats",
     "gridPos": { "h": 23, "w": 9, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  distinct date, home_participant, away_participant\nFROM\n  following_setka_cup_others_men\nWHERE \n  (home_participant in ($setka_men) or away_participant in ($setka_men)) and date>=now()\nORDER BY date asc\n"
      }
     ]
    },
    {
     "title": "Stats for sets",
     "type": "table",
     "description": "Stats for player who plays in the next 8h",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 9 },
     "targets": [
      {
       "rawSql": "select \n  player, \n  \"sets.count\" as matches,\n  \"sets.mean\" as \"mean\", \"sets.std\" as \"std\", \n  \"sets.25\" as  \"25%\", \"sets.50\" as \"50%\", \"sets.75\" as \"75%\"\nfrom stats_setka_cup_others_men\nwhere player in ($setka_men)\norder by player asc"
      }
     ]
    },
    {
     "title": "Stats for points",
     "type": "table",
     "description": "Stats for player who plays in the next 8h",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 21 },
     "targets": [
      {
       "rawSql": "select\n  player,\n  \"points.count\" as matches,\n  \"points.mean\" as \"mean\", \"points.std\" as \"std\", \"points.min\" as \"min\",\n  \"points.max\" as \"max\", \"points.25\" as \"25%\", \"points.50\" as \"50%\", \"points.75\" as \"75%\"\nfrom stats_setka_cup_others_men\nwhere player in ($setka_men)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pro League Men",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "options": {
      "content": "- **Stats for sets**: media de sets con valores positivos y negativos y su correspondiente desviación típica (std). Valores negativos indican que el jugador ha perdido más sets de los que ha ganado (y viceversa). Si `mean = 0` entonces el jugador ha ganado tantos particos como los que ha perdido. El valor de **%** indica el número de sets ganados/perdidos según el percentil (25, 50, 75). Por ejemplo, si `25% = 2` entonces podemos decir que para el **25%** total de partidos, el jugador ha ganado **2** sets por encima de sus oponentes. Otro ejemplo: `75% = -1` entonces el **75%** de partidos, el jugador ha finalizado con **1** set por debajo de su oponente. En resumen, valores positivos indican buenos jugadores mientras que valores negativos son sinónimos de malos jugadores.\n - **Stats for points**: aplica la misma dinámica explicada que para *Stats for sets* pero esta vez para la diferencia entre puntos totales.\n\n ---- \n\n- **Stats for sets**: sets mean with values -/+ corresponding with typical desviation (std). Mean negative values ​​indicate that the player has lost more sets than he has won (and viceversa). If `mean = 0` then the player has won the same number of sets he lost. The interpretation of **%** is a bit different, it indicate in which percentile are the number of sets. For example, if `25% = 2` then we can say that for the **25%** total of matches, the player has won with **2** sets above of his opponent. Another example: if `75% = -1` then for the **75%** total of matches, the player has lost with **1** sets below his opponent. Consider that positive values indicate a good player and negative values are synonymous of bad players.\n - **Stats for points**: the same as *Stats for sets* but in this case for total points differences."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Next matches",
     "type": "table",
     "description": "Next matches for the player who has at least 1 stats",
     "gridPos": { "h": 24, "w": 9, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\n  distinct date, home_participant, away_participant\nFROM\n  following_liga_pro_others_men\nWHERE \n  (home_participant in ($pro_men) or away_participant in ($pro_men)) and date>=now()\nORDER BY date asc\n"
      }
     ]
    },
    {
     "title": "Stats for sets",
     "type": "table",
     "description": "Stats for player who plays in the next 8h",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 36 },
     "targets": [
      {
       "rawSql": "select \n  player, \n  \"sets.count\" as matches,\n  \"sets.mean\" as \"mean\", \"sets.std\" as \"std\", \n  \"sets.25\" as  \"25%\", \"sets.50\" as \"50%\", \"sets.75\" as \"75%\"\nfrom stats_liga_pro_others_men\nwhere player in ($pro_men)\norder by player asc"
      }
     ]
    },
    {
     "title": "Stats for points",
     "type": "table",
     "description": "Stats for player who plays in the next 8h",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 48 },
     "targets": [
      {
       "rawSql": "select\n  player,\n  \"points.count\" as matches,\n  \"points.mean\" as \"mean\", \"points.std\" as \"std\", \"points.min\" as \"min\",\n  \"points.max\" as \"max\", \"points.25\" as \"25%\", \"points.50\" as \"50%\", \"points.75\" as \"75%\"\nfrom stats_liga_pro_others_men\nwhere player in ($pro_men)"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Cloud Storage Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Storage Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 6 charts for the related [Cloud Storage metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-storage), including `Total object count`, `Total bytes`, `Bucket object count`, `Bucket total bytes`, `Bucket - Received/Sent Bytes`, and `Bucket - Request count`."
   }
  },
  {
   "title": "Total object count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/object_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bucket object count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/object_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Bucket total bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bucket - Received bytes, Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Bucket - Request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/api/request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}
{
 "title": "Network TCP Load Balancer Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Network TCP Load Balancer Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 5 charts for the related [network TCP load balancer metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing), including `RTT latencies`, `Ingress TCP packets`, `Ingress TCP bytes`, `Egress TCP packets`, and `Egress TCP bytes`."
   }
  },
  {
   "title": "RTT latencies [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Ingress TCP packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/ingress_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Ingress TCP bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/ingress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress TCP packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/egress_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress TCP bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/egress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}
{
 "title": "GCE Network Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GCE Network Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 4 charts for the related [GCE VM networking metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-networking), including `GCE VM Instance - Egress bytes`, `GCE VM Instance - Ingress bytes`, `Number of probes`, and `GCE VM Instance - RTT latencies`."
   }
  },
  {
   "title": "GCE VM Instance - Egress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/egress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Ingress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/ingress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Number of probes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_COUNT",
      "filters": [
       "resource.type",
       "=",
       "gce_zone_network_health"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/cloud_netslo/active_probing/probe_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - RTT latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}
{
 "title": "Firewall Insights Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Firewall Insights Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 2 charts for the [Firewall insights metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-firewallinsights). Those two metrics are `Subnet Firewall Hit Counts` and `VM Firewall Hit Counts`."
   }
  },
  {
   "title": "Subnet Firewall Hit Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_subnetwork"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firewallinsights.googleapis.com/subnet/firewall_hit_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "VM Firewall Hit Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firewallinsights.googleapis.com/vm/firewall_hit_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}
{
 "title": "GCE VM Instance Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GCE VM Instance Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 10 charts for the related [GCE VM metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-compute), including metrics for CPU, disk read/write, and network."
   }
  },
  {
   "title": "GCE VM Instance - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}}",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "s{uptime}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Disk read operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent packets count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/nat/sent_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "{packet}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}