apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
  labels:
    app: natura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natura
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: natura
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: MYSQL_ROOT_PASSWORD
        # volumeMounts:
      #   - name: mysql-data
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-data
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
