# kubectl get certificate -n minio
# kubectl describe certificate minio-cert -n minio
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: minio
spec:
  dnsNames:
    - minio.felagonell.com
  secretName: minio-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
