FROM debian:jessie-slim

RUN apt update &&\
    apt upgrade -y &&\
    apt install wget -y &&\
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# The first line ALWAYS fails ->  "|| true" command to continue
RUN dpkg -i google-chrome-stable_current_amd64.deb || true && \
    apt --fix-broken install -y && \
    dpkg -i google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb

# Change 1000 with the result from 'id -u' command (user id) & 'id -g' command (group id)
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/chrome && \
    echo "chrome:x:${uid}:${gid}:chrome,,,:/home/chrome:/bin/bash" >> /etc/passwd && \
    echo "chrome:x:${uid}:" >> /etc/group && \
    mkdir /etc/sudoers.d && \
    echo "chrome ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/chrome && \
    chmod 0440 /etc/sudoers.d/chrome && \
    chown ${uid}:${gid} -R /home/chrome && \
    mkdir /home/chrome/Downloads && \
    chmod 777 /home/chrome/Downloads

USER chrome

ENV HOME /home/chrome

WORKDIR /home/chrome

CMD /usr/bin/google-chrome
