apiVersion: v2
appVersion: 3.9.44
dependencies:
- name: common
  repository: file://../common
  version: ~1.3.0
description: Sysdig Admission Controller using Sysdig Secure inline image scanner
home: https://sysdiglabs.github.io/admission-controller/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
maintainers:
- name: sysdiglabs
name: admission-controller
type: application
version: 0.16.2
