version: '3'

services:
  filebeat:
    container_name: filebeat
    build: ./filebeat
    image: docker-filebeat:7.8.0
    user: root
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

volumes:
  filebeat:

networks:
  elk:

