version: '3'

services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - ./environment/mysql.env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-wordpress-data:/var/lib/mysql
    networks:
      - wordpress-net

  wordpress:
    container_name: wp-web
    image: wordpress:php7.4
    depends_on:
      - mysql
    env_file:
      - ./environment/wordpress.env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-net

volumes:
  mysql-wordpress-data:      

networks:
  wordpress-net: