version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - jenkins-net

volumes:
  registry-data:

networks:
  jenkins-net:
