version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible-docker
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
  git:
    container_name: git-server
    hostname: gitlab.example.com
    image: gitlab/gitlab-ce:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - jenkins-net

volumes:
  jenkins-home:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  jenkins-net:
