apiVersion: v2
appVersion: 1.39.0
dependencies:
- name: common
  repository: file://../common
  version: ~1.3.0
description: Sysdig KSPM collector
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: chen.shmilovich@sysdig.com
  name: chen-shmilovich-sysdig
name: kspm-collector
sources:
- https://app.sysdigcloud.com/#/settings/user
- https://github.com/draios/sysdig
version: 0.15.3
