apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: spotfire
  name: spotfire
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "9443"
      port: 9443
      targetPort: 9443
    - name: "9080"
      port: 9080
      targetPort: 9080
    - name: "5701"
      port: 5701
      targetPort: 5701
  selector:
    io.kompose.service: spotfire
status:
  loadBalancer: {}
