apiVersion: v1
kind: Secret
metadata:
  name: pinpon-secrets
type: Opaque
data:
  ### Postgres
  POSTGRES_USER: cHNxbHBpbnBvbg==
  POSTGRES_PASSWORD: ZW1lZ240aEMuZWZ3Mw==
  POSTGRES_DB: bXlzdXBlcmRi
  GRAFANA_USER: Z3JhZmFuYQ== # grafana datasource
  GRAFANA_PASSWORD: andlbmZpZSFU # grafana datasource
  AIRFLOW_PSQL_USER: YWlyZmxvdw== # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_PASSWORD: ZW1lZ240aEMu # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_DB: YWlyZmxvdw== # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  CUSTOM_USER: cGlucG9uZmVs
  CUSTOM_PASSWORD: ZW1lZ240aEMu
  CUSTOM_DB: cGlucG9u # grafana datasource
  ### Telegram
  TOKEN_BOT: Y2hhbmdlbWUK
