apiVersion: v1
kind: Service
metadata:
  name: psql-pinpon-svc
  namespace: pinpon
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: psql-pinpon
  type: ClusterIP
