version: '3'

services:
  depserver1:
    container_name: depserver1
    hostname: depserver1
    image: splunk/splunk:latest
    environment:
      - SPLUNK_START_ARGS: "--accept-license"
      - SPLUNK_ROLE: "splunk_deployment_server"
      - SPLUNK_PASSWORD: changeme
    networks:
      - splunk-net

networks:
  splunk-net:
