apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  # PostgreSQL
  POSTGRES_DB: a2V5Y2xvYWs= # keycloak
  POSTGRES_USER: a2V5Y2xvYWs= # keycloak
  POSTGRES_PASSWORD: OEF3ZWZiVW8yOC4=
  # Keycloak
  DB_DATABASE: a2V5Y2xvYWs= # POSTGRES_DB
  DB_USER: a2V5Y2xvYWs= # POSTGRES_USER
  DB_PASSWORD: OEF3ZWZiVW8yOC4= # POSTGRES_PASSWORD
  KEYCLOAK_USER: YWRtaW4=
  KEYCLOAK_PASSWORD: NndlZjgyLlNE # 6wef82.SD
