version: '3'

services:
  nessus:
    container_name: nessus
    image: tenable/nessus:10.6.4-ubuntu
    env_file:
      - ./environment/nessus.env
    ports:
      - "8834:8834"
    networks:
      - nessus

networks:
  nessus:
