services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - 8069:8069
    environment:
      - HOST=db
      - PORT=5432
      - PASSWORD=changeme
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-network
  db:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 5s
      retries: 5
    volumes:
      - odoo-db-data:/var/lib/postgresql
    networks:
      - odoo-network
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-network:
    driver: bridge
