# https://artifacthub.io/packages/helm/bitnami/rabbitmq

# Requested RabbitMQ "nodes" (StatefulSet Pods), not to be confused with Kubernetes "nodes".
replicaCount: 3

# Exposed dashboard as NodePort for demonstration purposes.
service:
  type: NodePort 
  nodePorts:
    manager: 31000

# Admin credentials, use these for sign in to RabbitMQ dashboard
auth:
  username: guest
  password: guest

persistence:
  enabled: false
