apiVersion: v2
dependencies:
- alias: admissionController
  condition: admissionController.enabled
  name: admission-controller
  repository: file://../admission-controller
  version: ~0.16.2
- alias: agent
  condition: agent.enabled
  name: agent
  repository: file://../agent
  version: ~1.23.3
- name: common
  repository: file://../common
  version: ~1.3.0
- alias: nodeAnalyzer
  condition: nodeAnalyzer.enabled
  name: node-analyzer
  repository: file://../node-analyzer
  version: ~1.27.4
- alias: clusterScanner
  condition: clusterScanner.enabled
  name: cluster-scanner
  repository: file://../cluster-scanner
  version: ~0.13.2
- alias: kspmCollector
  condition: kspmCollector.enabled,global.kspm.deploy
  name: kspm-collector
  repository: file://../kspm-collector
  version: ~0.15.3
- alias: rapidResponse
  condition: rapidResponse.enabled
  name: rapid-response
  repository: file://../rapid-response
  version: ~0.9.0
description: A chart with various Sysdig components for Kubernetes
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
maintainers:
- email: alberto.barba@sysdig.com
  name: AlbertoBarba
- email: adam.roberts@sysdig.com
  name: aroberts87
- email: francesco.furlan@sysdig.com
  name: francesco-furlan
- email: gerlando.falauto@sysdig.com
  name: iurly
- email: marcovito.moscaritolo@sysdig.com
  name: mavimo
name: sysdig-deploy
type: application
version: 1.52.6
