service:
  type: NodePort
  nodePort: 31111

postgresql:
  persistence:
    enabled: false

plugins:
  install:
    - 'https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/3.3.1/sonar-pmd-plugin-3.3.1.jar'
    - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/10.1/checkstyle-sonar-plugin-10.1.jar'
    - 'https://github.com/spotbugs/sonar-findbugs/releases/download/4.0.4/sonar-findbugs-plugin-4.0.4.jar'

# Many other plugins can be considered: https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/

# Chart issue reported: https://github.com/SonarSource/helm-chart-sonarqube/issues
# account:
#   currentAdminPassword: admin
#   adminPassword: 123
