{
 "title": "GCE Network Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GCE Network Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 4 charts for the related [GCE VM networking metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-networking), including `GCE VM Instance - Egress bytes`, `GCE VM Instance - Ingress bytes`, `Number of probes`, and `GCE VM Instance - RTT latencies`."
   }
  },
  {
   "title": "GCE VM Instance - Egress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/egress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Ingress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/ingress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Number of probes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_COUNT",
      "filters": [
       "resource.type",
       "=",
       "gce_zone_network_health"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/cloud_netslo/active_probing/probe_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - RTT latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/rtt",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}