metricbeat.modules:
  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"] 
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana.host: "kibana"
setup.kibana.protocol: "http"
setup.kibana.username: "elastic"
setup.kibana.password: "changeme"
