apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflow
  labels:
    app: airflow-worker
spec:
  replicas: 1 # test 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 50000
        runAsGroup: 50000
      containers:
        - name: airflow-worker
          image: apache/airflow:2.1.0
          imagePullPolicy: IfNotPresent
          resources:
          # 48.82% from 2CPU
          # 1.018GiB / 2.931Gi
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          args: ["celery", "worker"]
          securityContext:
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
            privileged: false
          # always fail
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - celery --app airflow.executors.celery_executor.app inspect ping -d "celery@${HOSTNAME}"
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          envFrom:
            - configMapRef:
                name: airflow-envs
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__CELERY__RESULT_BACKEND
            - name: AIRFLOW__CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__CELERY__BROKER_URL
            - name: _AIRFLOW_WWW_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: _AIRFLOW_WWW_USER_USERNAME
            - name: _AIRFLOW_WWW_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: _AIRFLOW_WWW_USER_PASSWORD
            - name: AIRFLOW_PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_PSQL_USER
            - name: AIRFLOW_PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_PSQL_PASSWORD
            - name: AIRFLOW_PSQL_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_PSQL_DB
            - name: CUSTOM_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: CUSTOM_USER
            - name: CUSTOM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: CUSTOM_PASSWORD
            - name: CUSTOM_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: CUSTOM_DB
