# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis-airflow
#   namespace: airflow
#   labels:
#     app: redis-airflow
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: redis-airflow
#   template:
#     metadata:
#       labels:
#         app: redis-airflow
#     spec:
#       restartPolicy: Always
#       terminationGracePeriodSeconds: 30
#       dnsPolicy: ClusterFirst
#       automountServiceAccountToken: false
#       containers:
#         - name: redis-airflow
#           image: redis:6.2
#           imagePullPolicy: IfNotPresent
#           resources:
#           # 2.332MiB / 2.931GiB without data
#             requests:
#               cpu: 100m
#               memory: 1024Mi
#             limits:
#             # need to test
#               cpu: 256m
#               memory: 4096Mi
#           command: ["redis-server"]
#           args: ["--requirepass", "${REDIS_PASSWORD}"]
#           securityContext:
#             allowPrivilegeEscalation: false
#             # readOnlyRootFilesystem: true
#             privileged: false
#           ports:
#             - containerPort: 6379
#               protocol: TCP
#           env:
#             - name: REDIS_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: airflow-secrets
#                   key: REDIS_PASSWORD
#