apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:changeme@psql-svc.airflow.svc.cluster.local/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6Y2hhbmdlbWVAcHNxbC1zdmMuYWlyZmxvdy5zdmMuY2x1c3Rlci5sb2NhbC9haXJmbG93
  # AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:changeme@psql-svc.airflow.svc.cluster.local/airflow
  # AIRFLOW__CELERY__RESULT_BACKEND: redis://:changeme@redis-svc.airflow.svc.cluster.local:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: ZGIrcG9zdGdyZXNxbDovL2FpcmZsb3c6Y2hhbmdlbWVAcHNxbC1zdmMuYWlyZmxvdy5zdmMuY2x1c3Rlci5sb2NhbC9haXJmbG93
  # AIRFLOW__CELERY__BROKER_URL: amqp://rabbitmq_user:changeme@rabbitmq-svc.airflow.svc.cluster.local:5672/my_vhost
  AIRFLOW__CELERY__BROKER_URL: YW1xcDovL3JhYmJpdG1xX3VzZXI6Y2hhbmdlbWVAcmFiYml0bXEtc3ZjLmFpcmZsb3cuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi9teV92aG9zdA==
  _AIRFLOW_WWW_USER_USERNAME: YWRtaW4= # admin
  _AIRFLOW_WWW_USER_PASSWORD: Y2hhbmdlbWU= # changeme
  ### Postgres
  POSTGRES_USER: Y2hhbmdlbWU= # changeme
  POSTGRES_PASSWORD: Y2hhbmdlbWU= # changeme
  POSTGRES_DB: bXlzdXBlcmRi # mysuperdb
  GRAFANA_USER: Z3JhZmFuYQ== # grafana
  GRAFANA_PASSWORD: Y2hhbmdlbWU= # changeme
  AIRFLOW_PSQL_USER: YWlyZmxvdw== # airflow see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_PASSWORD: Y2hhbmdlbWU= # changeme see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_DB: YWlyZmxvdw== # airflow see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  CUSTOM_USER: Y2hhbmdlbWU= # changeme
  CUSTOM_PASSWORD: Y2hhbmdlbWU= # changeme
  CUSTOM_DB: Y2hhbmdlbWU= # changeme
  ### Flower
  AIRFLOW__CELERY__FLOWER_BASIC_AUTH: dXNlcjE6Y2hhbmdlbWU= # user1:changeme user2 comma separated
  ### RabbitMQ
  RABBITMQ_ERLANG_COOKIE: bXlyYWJiaXRtcWVybGFuZ2Nvb2NraWU= # myrabbitmqerlangcoockie
  RABBITMQ_DEFAULT_USER: cmFiYml0bXFfdXNlcg== # rabbitmq_user
  RABBITMQ_DEFAULT_PASS: Y2hhbmdlbWU= # changeme
  RABBITMQ_DEFAULT_VHOST: bXlfdmhvc3Q= # my_vhost
  ### Redis
  # REDIS_PASSWORD: Y2hhbmdlbWU= # changeme
  