# Pending test
# Remember to put in namespace
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  commonName: "*.felagonell.com"
  dnsNames:
  - felagonell.com
  - "*.felagonell.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wildcard-felagonell-tls

