# kubectl get certificate -n jenkins
# kubectl describe certificate jenkins-cert -n jenkins
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
  namespace: jenkins
spec:
  dnsNames:
    - jenkins.felagonell.com
  secretName: jenkins-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
