apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-js
  labels:
    app: frontend-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-js
  template:
    metadata:
      labels:
        app: frontend-js
    spec:
      containers:
      - name: frontend
        image: k8s-js:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-js
  labels:
    app: frontend-js
spec:
  type: NodePort
  selector:
    app: frontend-js
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
