apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # echo -n '' | base64
  # Airflow
  # AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:emegn4hC.@psql-pinpon-svc.pinpon.svc.cluster.local/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6ZW1lZ240aEMuQHBzcWwtcGlucG9uLXN2Yy5waW5wb24uc3ZjLmNsdXN0ZXIubG9jYWwvYWlyZmxvdw==
  _AIRFLOW_WWW_USER_USERNAME: YWRtaW4= # admin
  _AIRFLOW_WWW_USER_PASSWORD: ZW1lZ240aEMu # emegn4hC.
  ### Postgres and Airflow. See pinpon app
  POSTGRES_USER: cHNxbHBpbnBvbg==
  POSTGRES_PASSWORD: ZW1lZ240aEMuZWZ3Mw==
  POSTGRES_DB: bXlzdXBlcmRi
  GRAFANA_USER: Z3JhZmFuYQ== # grafana datasource
  GRAFANA_PASSWORD: andlbmZpZSFU # grafana datasource
  AIRFLOW_PSQL_USER: YWlyZmxvdw== # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_PASSWORD: ZW1lZ240aEMu # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  AIRFLOW_PSQL_DB: YWlyZmxvdw== # see AIRFLOW__CORE__SQL_ALCHEMY_CONN
  CUSTOM_USER: cGlucG9uZmVs
  CUSTOM_PASSWORD: ZW1lZ240aEMu
  CUSTOM_DB: cGlucG9u # grafana datasource
  ### Minio
  MINIO_ACCESS_KEY: YWRtaW4= # minio-secrets
  MINIO_SECRET_KEY: ZW5mV0U5NC4haXdvZQ== # minio-secrets
  ### Telegram
  TOKEN_BOT: Y2hhbmdlbWUK
  CHAT_ID: Y2hhbmdlbWUK
  GROUP_ID: Y2hhbmdlbWUK
  CHANNEL_ID: Y2hhbmdlbWUK
