# kubectl get certificate -n airflow
# kubectl describe certificate airflow-cert -n airflow
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
  namespace: airflow
spec:
  dnsNames:
    - airflow.felagonell.com
  secretName: airflow-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
