version: "3.1"

services:
  db:
    image: mysql:8.1
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: myddbb
      MYSQL_USER: admin # mysql -u admin -p
      MYSQL_PASSWORD: changeme
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - mysql-net

volumes:
  mysql-data:

networks:
  mysql-net: