version: '3'

services:
  db:
    container_name: guacamole-db
    image: mysql:5.7
    env_file:
      - guacamole.env
    volumes:
      - $PWD/conf/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - $PWD/data:/var/lib/mysql
    networks:
      - guacamole-net

  daemon:
    container_name: guacamole-daemon
    image: guacamole/guacd
    depends_on:
      - db
    networks:
      - guacamole-net

  web:
    container_name: guacamole-web
    image: guacamole/guacamole
    env_file:
      - guacamole.env
    depends_on:
      - daemon
    networks:
      - guacamole-net

  proxy:
    container_name: guacamole-proxy
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - guacamole-net

networks:
  guacamole-net:
